server:
  port: 8080

spring:
  cloud:
    gateway:
      routes: # <-- Keep only this single 'routes' key
        - id: restaurant-service
          uri: lb://RESTAURANT-SERVICE
          predicates:
            - Path=/restaurants/**

        - id: user-service # <-- Add the second route here, as another item in the list
          uri: lb://USER-SERVICE
          predicates:
            - Path=/users/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
