server:
  port: 8080

spring:
  application:
    name: api-gateway
    
#  cloud:
#    gateway:
#      routes:
#        - id: user-service
#          uri: lb://USER-SERVICE
#          predicates:
#            - Path=/users/**
#
#        - id: tiffin-provider-service
#          uri: lb://TIFFIN-PROVIDER-SERVICE
#          predicates:
#            - Path=/providers/**
#
#        - id: subscription-service
#          uri: lb://SUBSCRIPTION-SERVICE
#          predicates:
#            - Path=/subscriptions/**
#
#        - id: menu-service
#          uri: lb://MENU-SERVICE
#          predicates:
#            - Path=/menu/**,/providers/*/menu/**,/public/providers/*/menu/**
#
#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8761/eureka

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false

management:
  endpoints:
    web:
      exposure:
        include: health
