server:
  port: 8081

spring:
  application:
    name: tiffin-provider-service

  # MongoDB configuration
  data:
    mongodb:
      uri: "mongodb+srv://princekr3006_tiffin-provider-service-db:qO4YWm2QmoZcy6OY@cluster0.jqbhtry.mongodb.net/?appName=Cluster0"
      database: tiffin-provider-service-db


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
