
"mongodb+srv://princekr3006_tiffin-provider-service-db:qO4YWm2QmoZcy6OY@cluster0.jqbhtry.mongodb.net/?appName=Cluster0"


      $env:PORT=8081
      $env:EUREKA_URL="http://localhost:8761/eureka"
      $env:MONGODB_URI="mongodb+srv://princekr3006_tiffin-provider-service-db:qO4YWm2QmoZcy6OY@cluster0.jqbhtry.mongodb.net/tiffin-provider-service-db?retryWrites=true&w=majority&appName=Cluster0"
      
      java -jar target/tiffin-provider-service-0.0.1-SNAPSHOT.jar
