
  $env:PORT=8083
  $env:EUREKA_URL="http://localhost:8761/eureka"
  $env:MONGODB_URI="mongodb+srv://subscription-service:2RszSHZhSwI00PJD@subscription-service.tqj0drk.mongodb.net/subscription-service?retryWrites=true&w=majority"
  
  java -jar target/subscription-service-0.0.1-SNAPSHOT.jar
