#server:
#  port: ${PORT:8082}
#
#spring:
#  application:
#    name: user-service
#
#  data:
#    mongodb:
#      uri: ${MONGODB_URI}
#      database: user-service-db
#
#management:
#  endpoints:
#    web:
#      exposure:
#        include: health,info
#
#eureka:
#  client:
#    enabled: false
#
#data:
#  mongodb:
#    uri: mongodb+srv://princekr3006_user-service:odg8aEhYPxcRbOaE@user-service.h9edwgs.mongodb.net/?appName=user-service
#    database: user-service-db

$env:MONGODB_URI="mongodb+srv://princekr3006_user-service:odg8aEhYPxcRbOaE@user-service.h9edwgs.mongodb.net/?appName=user-service"
java -jar target/user-service-0.0.1-SNAPSHOT.jar
